# DEEP LEARNING

## Pytorch Basic

In [1]:
import torch

In [2]:
torch.cuda.is_available() #kiem tra xem tren thiet bi co gpu hay ko

False

#### Dataset with pytorch

In [3]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [4]:
df = pd.read_csv('Iris.csv') #load du lieu
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica


In [5]:
df.shape #kich thuoc du lieu


(150, 6)

In [6]:
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import LabelEncoder 

le = LabelEncoder() #chuyen doi ten loai hoa thanh so
x = df.drop(["Species"], axis=1).values #lay tat ca cac cot ngoai tru cot Species
y = le.fit_transform(df["Species"].values) #chuyen doi ten loai hoa thanh so

# chia du lieu voi test size = 20%
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42) # chia du lieu
x_test = torch.FloatTensor(x_test) # chuyen doi du lieu ve dang tensor
x_train = torch.FloatTensor(x_train)
y_test = torch.LongTensor(y_test).reshape(-1,) # chuyen doi du lieu ve dang tensor va reshape de phu hop voi model
y_train = torch.LongTensor(y_train).reshape(-1,) #longtensor la mot tensor chua so nguyen lon 64-bit(int64)

In [7]:
len(y_train)

120

In [8]:
labels,counts = y_train.unique(return_counts=True) #dem so luong tung loai hoa trong du lieu train
print(labels)
print(counts)

tensor([0, 1, 2])
tensor([40, 41, 39])


In [9]:
# tinh dao ham bang pytorch
# cho y = 2x^4 + x^3 + 3x^2 + 5x + 1
# tinh y'
x = torch.tensor(2.0, requires_grad=True) #tao mot tensor co gia tri 2.0 va yeu cau tinh dao ham
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
y.grad_fn #ham tinh dao ham
y.backward() #tinh dao ham
x.grad #in ra gia tri dao ham tai diem x = 2.0


tensor(93.)

## BTVN 1:
## cho y = 5x^5 + 6x^3 - 3x + 1
## cho biet do doc cua da thuc tren o diem nao

In [10]:
import torch
import numpy as np

def calculate_gradient_at_point(x_value):
    """
    Tính độ dốc của hàm y = 5x^5 + 6x^3 - 3x + 1 tại điểm x_value
    """
    x = torch.tensor(x_value, dtype=torch.float32, requires_grad=True)
    y = 5 * x**5 + 6 * x**3 - 3 * x + 1
    y.backward()
    return x.grad.item()

def find_points_with_specific_gradient(target_gradient):
    """
    Tìm tất cả các điểm x mà tại đó độ dốc = target_gradient
    """
    # Giải phương trình: 25x^4 + 18x^2 - 3 = target_gradient
    # Tức là: 25x^4 + 18x^2 - (3 + target_gradient) = 0
    
    # Đặt t = x^2, phương trình trở thành: 25t^2 + 18t - (3 + target_gradient) = 0
    a = 25
    b = 18
    c = -(3 + target_gradient)
    
    discriminant = b**2 - 4*a*c
    
    if discriminant < 0:
        return []  # Không có nghiệm thực
    
    solutions = []
    
    # Tính nghiệm t
    sqrt_disc = np.sqrt(discriminant)
    t1 = (-b + sqrt_disc) / (2*a)
    t2 = (-b - sqrt_disc) / (2*a)
    
    # Kiểm tra và tính nghiệm x từ t
    if t1 >= 0:
        x1 = np.sqrt(t1)
        x2 = -np.sqrt(t1)
        solutions.extend([x1, x2])
    
    if t2 >= 0 and abs(t2 - t1) > 1e-10:  # Tránh trùng lặp
        x3 = np.sqrt(t2)
        x4 = -np.sqrt(t2)
        solutions.extend([x3, x4])
    
    # Làm tròn và loại bỏ trùng lặp
    solutions = list(set([round(x, 6) for x in solutions]))
    return sorted(solutions)

def main():
    print("=" * 60)
    print("TÍNH ĐỘ DỐC CỦA HÀM: y = 5x^5 + 6x^3 - 3x + 1")
    print("=" * 60)
    
    # 1. Tính độ dốc tại một số điểm cụ thể
    print("\n1. ĐỘ DỐC TẠI CÁC ĐIỂM CỤ THỂ:")
    
    test_points = [-2, -1.5, -1, -0.5, 0, 0.5, 1, 1.5, 2]
    
    for x_val in test_points:
        gradient = calculate_gradient_at_point(x_val)
        print(f"   Tại x = {x_val:5.1f}: dy/dx = {gradient:8.4f}")
    
    # 2. Tìm điểm có độ dốc = 0 (điểm cực trị)
    print("\n2. ĐIỂM CỰC TRỊ (độ dốc = 0):")
    zero_gradient_points = find_points_with_specific_gradient(0)
    
    if zero_gradient_points:
        print(f"   Tìm thấy {len(zero_gradient_points)} điểm:")
        for i, x in enumerate(zero_gradient_points, 1):
            y = 5*x**5 + 6*x**3 - 3*x + 1
            gradient_check = calculate_gradient_at_point(x)
            print(f"   Điểm {i}: x = {x:7.4f}, y = {y:7.4f}, dy/dx = {gradient_check:.10f}")
    else:
        print("   Không tìm thấy điểm nào có độ dốc = 0")
    
    # 3. Tìm điểm với độ dốc cụ thể khác
    print("\n3. TÌM ĐIỂM VỚI ĐỘ DỐC KHÁC:")
    
    target_gradients = [-5, -3, -1, 10, 50, 100]
    
    for target in target_gradients:
        points = find_points_with_specific_gradient(target)
        
        if points:
            print(f"   Độ dốc = {target:4}: Tìm thấy {len(points)} điểm")
            for x in points:
                y = 5*x**5 + 6*x**3 - 3*x + 1
                print(f"        x = {x:7.4f}, y = {y:7.4f}")
        else:
            print(f"   Độ dốc = {target:4}: Không có điểm nào")
    
    # 4. Tính độ dốc nhỏ nhất có thể
    print("\n4. PHÂN TÍCH ĐỘ DỐC:")
    
    # Đạo hàm: 25x^4 + 18x^2 - 3
    # Đây là hàm bậc 4, hệ số dương, nên có giá trị nhỏ nhất tại x = 0
    min_gradient = calculate_gradient_at_point(0)
    print(f"   Độ dốc nhỏ nhất có thể: {min_gradient} (tại x = 0)")
    print(f"   Công thức tổng quát: dy/dx = 25x^4 + 18x^2 - 3")
    print(f"   Với mọi x, dy/dx ≥ {min_gradient}")
    
    # 5. Nhập điểm từ người dùng
    print("\n5. TÍNH ĐỘ DỐC TẠI ĐIỂM TÙY CHỌN:")
    
    while True:
        try:
            user_input = input("\nNhập giá trị x (hoặc 'q' để thoát): ")
            
            if user_input.lower() == 'q':
                break
                
            x_val = float(user_input)
            gradient = calculate_gradient_at_point(x_val)
            y_val = 5*x_val**5 + 6*x_val**3 - 3*x_val + 1
            
            print(f"   Tại x = {x_val}:")
            print(f"   - Giá trị hàm số: y = {y_val}")
            print(f"   - Độ dốc: dy/dx = {gradient}")
            print(f"   - Công thức kiểm tra: 25*({x_val})⁴ + 18*({x_val})² - 3 = {25*x_val**4 + 18*x_val**2 - 3}")
            
        except ValueError:
            print("Vui lòng nhập số hợp lệ!")
        except Exception as e:
            print(f"Lỗi: {e}")

if __name__ == "__main__":
    main()

TÍNH ĐỘ DỐC CỦA HÀM: y = 5x^5 + 6x^3 - 3x + 1

1. ĐỘ DỐC TẠI CÁC ĐIỂM CỤ THỂ:
   Tại x =  -2.0: dy/dx = 469.0000
   Tại x =  -1.5: dy/dx = 164.0625
   Tại x =  -1.0: dy/dx =  40.0000
   Tại x =  -0.5: dy/dx =   3.0625
   Tại x =   0.0: dy/dx =  -3.0000
   Tại x =   0.5: dy/dx =   3.0625
   Tại x =   1.0: dy/dx =  40.0000
   Tại x =   1.5: dy/dx = 164.0625
   Tại x =   2.0: dy/dx = 469.0000

2. ĐIỂM CỰC TRỊ (độ dốc = 0):
   Tìm thấy 2 điểm:
   Điểm 1: x = -0.3736, y =  1.7715, dy/dx = 0.0000072122
   Điểm 2: x =  0.3736, y =  0.2285, dy/dx = 0.0000072122

3. TÌM ĐIỂM VỚI ĐỘ DỐC KHÁC:
   Độ dốc =   -5: Không có điểm nào
   Độ dốc =   -3: Tìm thấy 1 điểm
        x =  0.0000, y =  1.0000
   Độ dốc =   -1: Tìm thấy 2 điểm
        x = -0.3128, y =  1.7398
        x =  0.3128, y =  0.2602
   Độ dốc =   10: Tìm thấy 2 điểm
        x = -0.6678, y =  0.5523
        x =  0.6678, y =  1.4477
   Độ dốc =   50: Tìm thấy 2 điểm
        x = -1.0676, y = -10.0348
        x =  1.0676, y = 12.0348
   Độ 

## # BTVN 2:
## tao mot tensor ban dau co gia tri la 2
## dinh nghia ham so va tinh gradiant
## y = x^3 + 2x^2 + 5x + 1
## hay tinh dy/dx tai gia tri cua x 
## dung phuong phap Gradiant Descent voi learning rate alpha = 0.01 de cap nhat gia tri cua x sau 10 vong lap

In [11]:
import torch

# BTVN 2: Gradient Descent với y = x^3 + 2x^2 + 5x + 1

# 1. Tạo tensor ban đầu
x = torch.tensor(2.0, requires_grad=True)

# 2. Định nghĩa hàm số
def f(x):
    return x**3 + 2*x**2 + 5*x + 1

# 3. Gradient Descent
learning_rate = 0.01
iterations = 10

print("Gradient Descent: y = x^3 + 2x^2 + 5x + 1")
print("=" * 50)
print(f"Bắt đầu với x = {x.item():.4f}")

for i in range(iterations):
    # Tính giá trị hàm số
    y = f(x)
    
    # Tính gradient
    y.backward()
    
    # In kết quả
    print(f"Vòng {i+1:2d}: x = {x.item():8.4f}, y = {y.item():8.4f}, dy/dx = {x.grad.item():8.4f}")
    
    # Cập nhật x (gradient descent)
    with torch.no_grad():
        x -= learning_rate * x.grad
    
    # Reset gradient
    x.grad.zero_()

print("=" * 50)
print(f"Kết thúc: x = {x.item():.4f}, y = {f(x).item():.4f}")

Gradient Descent: y = x^3 + 2x^2 + 5x + 1
Bắt đầu với x = 2.0000
Vòng  1: x =   2.0000, y =  27.0000, dy/dx =  25.0000
Vòng  2: x =   1.7500, y =  21.2344, dy/dx =  21.1875
Vòng  3: x =   1.5381, y =  17.0612, dy/dx =  18.2500
Vòng  4: x =   1.3556, y =  13.9448, dy/dx =  15.9357
Vòng  5: x =   1.1963, y =  11.5554, dy/dx =  14.0782
Vòng  6: x =   1.0555, y =   9.6814, dy/dx =  12.5641
Vòng  7: x =   0.9298, y =   8.1824, dy/dx =  11.3132
Vòng  8: x =   0.8167, y =   6.9624, dy/dx =  10.2679
Vòng  9: x =   0.7140, y =   5.9539, dy/dx =   9.3857
Vòng 10: x =   0.6202, y =   5.1087, dy/dx =   8.6346
Kết thúc: x = 0.5338, y = 4.3912


## # BTVN 3:
## tao mot tap du lieu gia lap voi x la so h hoc ngau nhien tu 1 - 10 va y la so dem duoc tinh theo cong thuc 
## y = 3x + 5 + noise voi noise la mot gia tri ngau nhien nho

## 1 khoi tao tham so W va b ngau nhien voi requies_grad = True
## 2 tinh MSE
## 3 tinh Gradiant
## 4 cap nhat W va b theo phuong phap Gradiant Descent voi learning rate alpha = 0.01
## 5 lap lai 100 lan de xem su hoi tu cua mo hinh the nao

In [12]:
import torch
import numpy as np

# Tạo dữ liệu giả lập
np.random.seed(42)
x_data = np.random.uniform(1, 10, 50)          # Số giờ học: 50 điểm từ 1-10 giờ
noise = np.random.normal(0, 1.5, 50)           # Noise nhỏ
y_data = 3 * x_data + 5 + noise                # y = 3x + 5 + noise

# Chuyển sang tensor
x_tensor = torch.tensor(x_data, dtype=torch.float32)
y_tensor = torch.tensor(y_data, dtype=torch.float32)

# 1. Khởi tạo tham số W và b ngẫu nhiên
W = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print("=" * 60)
print("BÀI TẬP 3: HỒI QUY TUYẾN TÍNH")
print("=" * 60)
print(f"Dữ liệu: 50 điểm, x ∈ [1, 10] giờ học")
print(f"Công thức thực: y = 3x + 5 + noise")
print(f"Khởi tạo: W = {W.item():.4f}, b = {b.item():.4f}")
print("=" * 60)

# 2. Hàm tính MSE
def mse_loss(y_pred, y_true):
    return torch.mean((y_pred - y_true) ** 2)

# Gradient Descent
learning_rate = 0.01
epochs = 100

print("\nTIẾN TRÌNH HUẤN LUYỆN:")
print("-" * 60)

for epoch in range(epochs):
    # Dự đoán
    y_pred = W * x_tensor + b
    
    # Tính MSE loss
    loss = mse_loss(y_pred, y_tensor)
    
    # 3. Tính gradient (tự động với backward)
    loss.backward()
    
    # 4. Cập nhật W và b với Gradient Descent
    with torch.no_grad():
        W -= learning_rate * W.grad
        b -= learning_rate * b.grad
        
        # Reset gradient
        W.grad.zero_()
        b.grad.zero_()
    
    # In kết quả mỗi 25 epoch
    if (epoch + 1) % 25 == 0:
        print(f"Epoch {epoch+1:3d}: W = {W.item():6.3f}, b = {b.item():6.3f}, Loss = {loss.item():7.3f}")

# Kết quả cuối cùng
print("-" * 60)
print("\nKẾT QUẢ SAU 100 EPOCH:")
print(f"Giá trị thực tế: W = 3.0, b = 5.0")
print(f"Giá trị học được: W = {W.item():.3f}, b = {b.item():.3f}")
print(f"Loss cuối cùng: {loss.item():.3f}")

# Tính R-squared để đánh giá
y_pred_final = W * x_tensor + b
ss_res = torch.sum((y_tensor - y_pred_final) ** 2)
ss_tot = torch.sum((y_tensor - torch.mean(y_tensor)) ** 2)
r_squared = 1 - (ss_res / ss_tot)

print(f"R² Score: {r_squared.item():.4f} (càng gần 1 càng tốt)")

# Dự đoán thử
print("\nVÍ DỤ DỰ ĐOÁN:")
test_hours = [2, 5, 8, 10]
for hours in test_hours:
    predicted = W.item() * hours + b.item()
    actual = 3 * hours + 5  # Không có noise
    print(f"  {hours} giờ học: Dự đoán = {predicted:.1f} điểm, Thực tế ≈ {actual} điểm")

BÀI TẬP 3: HỒI QUY TUYẾN TÍNH
Dữ liệu: 50 điểm, x ∈ [1, 10] giờ học
Công thức thực: y = 3x + 5 + noise
Khởi tạo: W = 0.0699, b = 1.4446

TIẾN TRÌNH HUẤN LUYỆN:
------------------------------------------------------------
Epoch  25: W =  3.422, b =  2.295, Loss =   3.606
Epoch  50: W =  3.377, b =  2.575, Loss =   3.282
Epoch  75: W =  3.337, b =  2.827, Loss =   3.018
Epoch 100: W =  3.301, b =  3.056, Loss =   2.803
------------------------------------------------------------

KẾT QUẢ SAU 100 EPOCH:
Giá trị thực tế: W = 3.0, b = 5.0
Giá trị học được: W = 3.301, b = 3.056
Loss cuối cùng: 2.803
R² Score: 0.9534 (càng gần 1 càng tốt)

VÍ DỤ DỰ ĐOÁN:
  2 giờ học: Dự đoán = 9.7 điểm, Thực tế ≈ 11 điểm
  5 giờ học: Dự đoán = 19.6 điểm, Thực tế ≈ 20 điểm
  8 giờ học: Dự đoán = 29.5 điểm, Thực tế ≈ 29 điểm
  10 giờ học: Dự đoán = 36.1 điểm, Thực tế ≈ 35 điểm


In [13]:
torch.__version__

'2.9.1+cpu'

In [14]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [15]:
x = torch.from_numpy(arr) #chuyen doi tu numpy array sang pytorch tensor
print(x)
print(x.type())
print(x.dtype)

tensor([1, 2, 3, 4, 5])
torch.LongTensor
torch.int64


In [16]:
arr2 = np.arange(0.,12.).reshape(4,3) #tao mot numpy array 0 den 11 co 4 hang 3 cot
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [17]:
x2 = torch.from_numpy(arr2) #chuyen doi tu numpy array sang pytorch tensor
print(x2)
print(x2.type()) 

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [18]:
# copy and sharing
x = torch.from_numpy(arr) #chuyen doi tu numpy array sang pytorch tensor
print(x)

tensor([1, 2, 3, 4, 5])


In [19]:
arr[0] = 99
print(x)

tensor([99,  2,  3,  4,  5])


In [20]:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [21]:
arr[0] = 99
print(x)

tensor([0, 1, 2, 3, 4])


## BTVN 4
## giai thich 2 truong hop o tren

#### PyTorch cung cấp hai cách chuyển đổi từ NumPy array sang tensor với hành vi khác nhau về quản lý bộ nhớ.
#### Trường hợp 1: torch.from_numpy() - CHIA SẺ BỘ NHỚ
#### vì là chia sẻ bộ nhớ với array gốc nên khi thay đổi giá trị trong array thì cũng sẽ thay đổi theo vì chung một bộ nhớ

#### Trường hợp 2: torch.tensor() - SAO CHÉP BỘ NHỚ
#### còn trường hợp này chỉ sao chép bộ nhớ lúc tạo tensor sang một bộ nhớ nên khi có lệnh thay đổi ở array gốc thì nó không thay đổi cì khác bộ nhớ


## BTVN 5
## tao tensor voi
## empty


In [22]:
import torch

# Tạo tensor với giá trị rác (không khởi tạo)
empty_tensor = torch.empty(2, 3)  # 2x3 tensor với giá trị rác
print("Empty Tensor (2x3):")
print(empty_tensor)
print(f"Kích thước: {empty_tensor.shape}\n")

# Tensor 1 chiều
empty_1d = torch.empty(5)
print("Empty Tensor (1D, size=5):")
print(empty_1d)
print(f"Kích thước: {empty_1d.shape}\n")

# Tensor 3 chiều
empty_3d = torch.empty(2, 3, 4)
print("Empty Tensor (2x3x4):")
print(f"Kích thước: {empty_3d.shape}")

Empty Tensor (2x3):
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Kích thước: torch.Size([2, 3])

Empty Tensor (1D, size=5):
tensor([0., 0., 0., 0., 0.])
Kích thước: torch.Size([5])

Empty Tensor (2x3x4):
Kích thước: torch.Size([2, 3, 4])


## Zeros

In [27]:
import torch

# Tensor toàn số 0
zeros_tensor = torch.zeros(2, 3)  # 2x3 tensor toàn số 0
print("Zeros Tensor (2x3):")
print(zeros_tensor)
print(f"Kích thước: {zeros_tensor.shape}\n")

# Với dtype cụ thể
zeros_int = torch.zeros(3, 4, dtype=torch.int32)
print("Zeros Tensor (int32, 3x4):")
print(zeros_int)
print(f"Dtype: {zeros_int.dtype}\n")

# Tensor 1 chiều toàn 0
zeros_1d = torch.zeros(5)
print("Zeros Tensor (1D, size=5):")
print(zeros_1d)

Zeros Tensor (2x3):
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Kích thước: torch.Size([2, 3])

Zeros Tensor (int32, 3x4):
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)
Dtype: torch.int32

Zeros Tensor (1D, size=5):
tensor([0., 0., 0., 0., 0.])


## ones

In [26]:
import torch

# Tensor toàn số 1
ones_tensor = torch.ones(2, 3)  # 2x3 tensor toàn số 1
print("Ones Tensor (2x3):")
print(ones_tensor)
print(f"Kích thước: {ones_tensor.shape}\n")

# Với dtype cụ thể
ones_float64 = torch.ones(3, 2, dtype=torch.float64)
print("Ones Tensor (float64, 3x2):")
print(ones_float64)
print(f"Dtype: {ones_float64.dtype}\n")

# Tensor với giá trị khác (full)
full_tensor = torch.full((2, 3), 7.5)  # 2x3 tensor với tất cả giá trị = 7.5
print("Full Tensor (tất cả = 7.5):")
print(full_tensor)

Ones Tensor (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Kích thước: torch.Size([2, 3])

Ones Tensor (float64, 3x2):
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
Dtype: torch.float64

Full Tensor (tất cả = 7.5):
tensor([[7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000]])


## random

In [25]:
import torch

# Random uniform distribution [0, 1)
rand_tensor = torch.rand(2, 3)  # 2x3 tensor random từ uniform distribution
print("Random Tensor [0, 1) (2x3):")
print(rand_tensor)
print(f"Kích thước: {rand_tensor.shape}\n")

# Random normal distribution (mean=0, std=1)
randn_tensor = torch.randn(3, 2)  # 3x2 từ normal distribution
print("Random Normal Tensor (3x2):")
print(randn_tensor)
print(f"Mean: {randn_tensor.mean():.4f}, Std: {randn_tensor.std():.4f}\n")

# Random integers trong khoảng [low, high)
randint_tensor = torch.randint(low=0, high=10, size=(3, 4))
print("Random Integer Tensor [0, 10) (3x4):")
print(randint_tensor)
print(f"Min: {randint_tensor.min()}, Max: {randint_tensor.max()}\n")

# Random với seed để reproduce
torch.manual_seed(42)
reproducible_tensor = torch.rand(2, 2)
print("Reproducible Random Tensor (seed=42):")
print(reproducible_tensor)

Random Tensor [0, 1) (2x3):
tensor([[0.8166, 0.0705, 0.6110],
        [0.8422, 0.4060, 0.0505]])
Kích thước: torch.Size([2, 3])

Random Normal Tensor (3x2):
tensor([[-0.7455,  0.9664],
        [-0.2442,  0.0267],
        [-0.5768, -0.3813]])
Mean: -0.1591, Std: 0.6126

Random Integer Tensor [0, 10) (3x4):
tensor([[7, 6, 8, 3],
        [4, 7, 5, 5],
        [9, 7, 1, 5]])
Min: 1, Max: 9

Reproducible Random Tensor (seed=42):
tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])


## Resahpe voi view va view as

In [24]:
import torch

# Tạo tensor ban đầu
original = torch.arange(12)  # tensor([0, 1, 2, ..., 11])
print("Tensor ban đầu:")
print(original)
print(f"Kích thước: {original.shape}\n")

# 5.1 Sử dụng view() để reshape
# Reshape thành 3x4
reshaped_3x4 = original.view(3, 4)
print("Reshape thành 3x4 (view):")
print(reshaped_3x4)
print(f"Kích thước: {reshaped_3x4.shape}\n")

# Reshape thành 2x2x3
reshaped_2x2x3 = original.view(2, 2, 3)
print("Reshape thành 2x2x3 (view):")
print(reshaped_2x2x3)
print(f"Kích thước: {reshaped_2x2x3.shape}\n")

# Sử dụng -1 để tự động tính toán kích thước
auto_reshape = original.view(2, -1)  # Tự động tính: 12/2 = 6 → 2x6
print("Reshape với -1 (2x-1):")
print(auto_reshape)
print(f"Kích thước: {auto_reshape.shape}\n")

# 5.2 Sử dụng view_as() để reshape theo tensor khác
target_shape = torch.zeros(4, 3)  # Tensor mẫu 4x3
reshaped_as = original.view_as(target_shape)
print("Reshape theo tensor mẫu 4x3 (view_as):")
print(reshaped_as)
print(f"Kích thước: {reshaped_as.shape}\n")

# 5.3 So sánh với reshape()
# reshape() là alias của view() (trong hầu hết trường hợp)
reshaped_method = original.reshape(3, 4)
print("Reshape với reshape() method (3x4):")
print(reshaped_method)
print(f"Kích thước: {reshaped_method.shape}\n")

# 5.4 Kiểm tra chia sẻ bộ nhớ
print("KIỂM TRA CHIA SẺ BỘ NHỚ:")
print(f"original.data_ptr() = {original.data_ptr()}")
print(f"reshaped_3x4.data_ptr() = {reshaped_3x4.data_ptr()}")
print(f"Chia sẻ bộ nhớ? {original.data_ptr() == reshaped_3x4.data_ptr()}\n")

# 5.5 Thay đổi giá trị
print("THAY ĐỔI GIÁ TRỊ:")
reshaped_3x4[0, 0] = 99
print("Sau khi đặt reshaped_3x4[0,0] = 99:")
print(f"Original tensor: {original[0]}")
print(f"Reshaped tensor[0,0]: {reshaped_3x4[0,0]}")

Tensor ban đầu:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Kích thước: torch.Size([12])

Reshape thành 3x4 (view):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Kích thước: torch.Size([3, 4])

Reshape thành 2x2x3 (view):
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
Kích thước: torch.Size([2, 2, 3])

Reshape với -1 (2x-1):
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
Kích thước: torch.Size([2, 6])

Reshape theo tensor mẫu 4x3 (view_as):
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
Kích thước: torch.Size([4, 3])

Reshape với reshape() method (3x4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Kích thước: torch.Size([3, 4])

KIỂM TRA CHIA SẺ BỘ NHỚ:
original.data_ptr() = 6303603164032
reshaped_3x4.data_ptr() = 6303603164032
Chia sẻ bộ nhớ? True

THAY ĐỔI GIÁ TRỊ:
Sau khi đặt reshaped_3x4[0,0]